using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Reflection;
using System.Text.RegularExpressions;

namespace KamiYomu.CrawlerAgents.Core;
/// <summary>
/// Abstract base class for crawler agents that provides core HTTP client configuration,
/// logging, and request handling infrastructure.
/// </summary>
/// <remarks>
/// This class manages:
/// - HTTP client initialization with configurable handlers (SmartCrawler, FlareSolverr, Chromium)
/// - User agent string validation and management
/// - Request timeout configuration
/// - Logger integration for debugging and monitoring
/// 
/// Derived classes should implement specific crawling logic while leveraging the
/// configured HTTP client, user agent, and logging infrastructure provided by this base class.
/// </remarks>
public abstract partial class AbstractCrawlerAgent : IDisposable
{
    private bool _disposed = false;
    /// <summary>
    /// Browser user agent string to be used for HTTP requests. 
    /// This constant is used as a key in the options dictionary to specify a custom user agent for the crawler.
    /// </summary>
    private const string BrowserUserAgent = nameof(BrowserUserAgent);
    /// <summary>
    /// HTTP client timeout key in milliseconds. 
    /// This constant is used as a key in the options dictionary to specify a custom timeout for the HTTP client.
    /// </summary>
    private const string HttpClientTimeout = nameof(HttpClientTimeout);
    /// <summary>
    /// Logger instance for the crawler.
    /// This constant is used as a key in the options dictionary to specify a custom logger for the crawler.
    /// </summary>
    private const string KamiYomuILogger = nameof(KamiYomuILogger);
    /// <summary>
    /// FlareSolverr URL for the crawler.
    /// This constant is used as a key in the options dictionary to specify a custom FlareSolverr URL for the crawler.
    /// </summary>
    private const string FlareSolverrUrl = nameof(FlareSolverrUrl);
    /// <summary>
    /// FlareSolverr HTTP handler for the crawler.
    /// This constant is used as a key in the options dictionary to specify a custom FlareSolverr HTTP handler for the crawler.
    /// </summary>
    private const string FlareSolverrHttpHandler = nameof(FlareSolverrHttpHandler);
    /// <summary>
    /// Chromium HTTP handler for the crawler.
    /// This constant is used as a key in the options dictionary to specify a custom Chromium HTTP handler for the crawler.
    /// </summary>
    private const string ChromiumHttpHandler = nameof(ChromiumHttpHandler);
    /// <summary>
    /// Smart crawler HTTP handler for the crawler.
    /// This constant is used as a key in the options dictionary to specify a custom smart crawler HTTP handler for the crawler.
    /// </summary>
    private const string SmartCrawlerHttpHandler = nameof(SmartCrawlerHttpHandler);
    /// <summary>
    /// The HTTP client timeout value, in milliseconds.
    /// Used in the options dictionary to define a custom timeout for the HTTP client.
    /// </summary>
    protected const int HttpClientTimeoutValue = 60_000;
    /// <summary>
    /// User agent regex pattern to validate user agent strings. 
    /// This regex ensures that the user agent string consists of 
    /// printable ASCII characters and is between 1 and 512 characters long.
    /// </summary>
    protected readonly Regex UserAgentRegex = UserAgentRgx();

    /// <summary>
    /// Options dictionary containing configuration settings for the crawler agent.
    /// </summary>
    protected readonly IDictionary<string, object> Options = new Dictionary<string, object>();
    /// <summary>
    /// Timeout value for HTTP requests, in milliseconds. 
    /// This value can be configured via the options dictionary using the <see cref="HttpClientTimeout"/> key.
    /// </summary>
    protected readonly int TimeoutMilliseconds = HttpClientTimeoutValue;
    /// <summary>
    /// Http client default user agent string. 
    /// This value is either provided via the options dictionary using the <see cref="BrowserUserAgent"/> key or 
    /// generated by the <see cref="GetKamiYomuUserAgent"/> method if not specified.
    /// </summary>
    protected readonly string HttpClientDefaultUserAgent;
    /// <summary>
    /// Logger instance for the crawler agent. 
    /// This logger can be used for logging messages, errors, and diagnostics throughout the crawling process.
    /// </summary>
    protected readonly ILogger Logger;
    /// <summary>
    /// Default HTTP client handler used for making HTTP requests.
    /// This handler can be customized via the options dictionary 
    /// using the <see cref="SmartCrawlerHttpHandler"/>, 
    /// <see cref="FlareSolverrHttpHandler"/>, or 
    /// <see cref="ChromiumHttpHandler"/> keys,
    /// otherwise a new instance of <see cref="HttpClientHandler"/> is created.
    /// </summary>
    protected readonly HttpClientHandler DefaultHttpClientHandler;
    /// <summary>
    /// Default FlareSolverr HTTP client handler used for making HTTP requests.
    /// This handler can be customized via the options dictionary using the <see cref="FlareSolverrHttpHandler"/> key,
    /// otherwise a new instance of <see cref="HttpClientHandler"/> is created.
    /// </summary>
    protected readonly HttpClientHandler DefaultFlareSolverrHttpHandler;
    /// <summary>
    /// Default Chromium HTTP client handler used for making HTTP requests.
    /// This handler can be customized via the options dictionary using the <see cref="ChromiumHttpHandler"/> key,
    /// otherwise a new instance of <see cref="HttpClientHandler"/> is created.
    /// </summary>
    protected readonly HttpClientHandler DefaultChromiumHttpHandler;
    /// <summary>
    /// Initializes a new instance of the <see cref="AbstractCrawlerAgent"/> class with the specified options.
    /// </summary>
    /// <param name="options">A dictionary of options to configure the crawler agent.</param>
    protected AbstractCrawlerAgent(IDictionary<string, object> options)
    {
        options ??= new Dictionary<string, object>();
        Options = options;

        if (Options.TryGetValue(BrowserUserAgent, out var userAgentObj))
        {
            if (IsLikelyUserAgent(userAgentObj as string))
            {
                HttpClientDefaultUserAgent = userAgentObj as string;
            }
        }

        if (Options.TryGetValue(HttpClientTimeout, out var timeoutObj))
        {
            TimeoutMilliseconds = int.Parse(timeoutObj as string);
        }

        if (Options.TryGetValue(KamiYomuILogger, out var loggerObj))
        {
            Logger = loggerObj as ILogger;
        }

        if (string.IsNullOrWhiteSpace(HttpClientDefaultUserAgent))
        {
            HttpClientDefaultUserAgent = GetKamiYomuUserAgent();
        }

        DefaultFlareSolverrHttpHandler = ResolveHandler(options, FlareSolverrHttpHandler);
        DefaultChromiumHttpHandler = ResolveHandler(options, ChromiumHttpHandler);
        DefaultHttpClientHandler = ResolveFallbackHandler(
            options,
            SmartCrawlerHttpHandler,
            FlareSolverrHttpHandler,
            ChromiumHttpHandler
        );
    }

    /// <summary>
    /// Resolves the HTTP client handler from the provided options dictionary using the specified key.
    /// </summary>
    /// <param name="options">The dictionary of options to configure the HTTP client handler.</param>
    /// <param name="key">The key used to look up the HTTP client handler in the options dictionary.</param>
    /// <returns>The resolved HTTP client handler.</returns>
    private static HttpClientHandler ResolveHandler(
    IDictionary<string, object> options,
    string key)
    {
        return options.TryGetValue(key, out object value) &&
               value is HttpClientHandler handler
            ? handler
            : new HttpClientHandler();
    }

    /// <summary>
    /// Resolves the HTTP client handler from the provided options dictionary using a list of keys, returning the first valid handler found. 
    /// If none are found, a new instance of <see cref="HttpClientHandler"/> is returned.
    /// </summary>
    /// <param name="options">The dictionary of options to configure the HTTP client handler.</param>
    /// <param name="keys">The keys used to look up the HTTP client handler in the options dictionary.</param>
    /// <returns>The resolved HTTP client handler.</returns>
    private static HttpClientHandler ResolveFallbackHandler(
    IDictionary<string, object> options,
    params string[] keys)
    {
        foreach (string key in keys)
        {
            if (options.TryGetValue(key, out object value) &&
                value is HttpClientHandler handler)
            {
                return handler;
            }
        }

        return new HttpClientHandler();
    }



    /// <summary>
    /// Gets the version of the assembly that contains the crawler core. This can be useful for logging, diagnostics, or ensuring compatibility with other components.
    /// </summary>
    /// <returns>The version of the crawler core assembly.</returns>
    public Version GetCrawlerCoreAssemblyVersion()
    {
        var assembly = this.GetType().Assembly;
        return assembly.GetName().Version;
    }
    /// <summary>
    /// Gets the informational version of the assembly that contains the crawler core. This can be useful for logging, diagnostics, or ensuring compatibility with other components.
    /// </summary>
    /// <returns>The informational version of the crawler core assembly.</returns>
    public string GetCrawlerCoreInformationalVersion()
    {
        var attr = this.GetType().Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();
        return attr?.InformationalVersion ?? "unknown";
    }
    /// <summary>
    /// Gets the default user agent string for KamiYomu. 
    /// This method constructs a user agent string that includes the platform and architecture of the operating system, which can be useful for identifying the crawler in HTTP requests.
    /// </summary>
    /// <returns>The default user agent string for KamiYomu.</returns>
    protected virtual string GetKamiYomuUserAgent()
    {
        return $"KamiYomu-Agent/1.0 ({Environment.OSVersion.Platform}; {(Environment.Is64BitOperatingSystem ? "x64" : "x86")})";
    }
    /// <summary>
    /// Is likely user agent string. This method checks if the provided user agent string is valid and matches the expected format defined by the UserAgentRegex. 
    /// It returns true if the user agent is likely valid, and false otherwise.
    /// </summary>
    /// <param name="userAgent">The user agent string to validate.</param>
    /// <returns>True if the user agent is likely valid, false otherwise.</returns>
    protected virtual bool IsLikelyUserAgent(string userAgent)
    {
        return !string.IsNullOrWhiteSpace(userAgent) && UserAgentRegex.IsMatch(userAgent);
    }
    /// <summary>
    /// User agent regex. This method returns a compiled regular expression that matches valid user agent strings. The regex pattern ensures that the user agent consists of printable ASCII characters and is between 1 and 512 characters long.
    /// </summary>
    /// <returns>A compiled regular expression for validating user agent strings.</returns>
    [GeneratedRegex(@"^[ -~]{1,512}$", RegexOptions.Compiled)]
    protected static partial Regex UserAgentRgx();

    /// <inheritdoc/>
    public void Dispose()
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// Disposes of the resources used by the crawler agent. 
    /// This method is called by the public Dispose method and can be overridden in derived classes to release both managed and unmanaged resources.
    /// The disposing parameter indicates whether the method is being called from the Dispose method (true) or from a finalizer (false).
    /// </summary>
    /// <param name="disposing">True when called from <see cref="Dispose()"/>; false when called from a finalizer.</param>
    protected virtual void Dispose(bool disposing)
    {
        if (_disposed)
            return;

        if (disposing)
        {
            DefaultHttpClientHandler?.Dispose();
            DefaultFlareSolverrHttpHandler?.Dispose();
            DefaultChromiumHttpHandler?.Dispose();
        }
        _disposed = true;
    }
}
